#%RAML 1.0

title: Data import
version: v3.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Data import API
    content: API for uploading source records and processing them

types:
  errors: !include raml-storage/raml-util/schemas/errors.schema
  clientDefinition: !include clientDefinition.json


traits:
  validate: !include raml-storage/raml-util/traits/validation.raml
  language: !include raml-storage/raml-util/traits/language.raml
  pageable:  !include raml-storage/raml-util/traits/pageable.raml
  searchable: !include raml-storage/raml-util/traits/searchable.raml

resourceTypes:
  collection: !include raml-storage/raml-util/rtypes/collection.raml
  collection-item: !include raml-storage/raml-util/rtypes/item-collection.raml


/clients:
  post:
    body:
      application/json:
        type: clientDefinition
    responses:
      201:
      400:
        description: "Bad request"
        body:
          text/plain:
            example: "Bad request"
      422:
        description: "Unprocessable Entity"
        body:
          application/json:
            type: errors
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error"
